
seed_everything: 0

trainer:
  logger:
    class_path: lightning.pytorch.loggers.CSVLogger
   
    init_args:
      save_dir: 'my_logs'
      name: 'mobclip'
      version: 'china'
         

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: "val_loss"
        save_last: False
        filename: "{epoch}-{val_loss:.2f}"
        
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: "val_loss"
        patience: 10       
        mode: "min"
        verbose: true       
        
  max_epochs: 100

  
  
model:
  poi_dim: 1024
  demo_dim: 40
  image_dim: 768
  demo_hidden_dim: 64
  embedding_dim : 128
  mob_features_path:   # path for mobility LINE embeddings
  demo_scale: 0.7
  image_scale: 0.2
  poi_scale: 0.5
  learning_rate: 0.001
  weight_decay: 0.001
 

data:
  mob_path:     # path for mobility LINE embeddings
  poi_path:     # path for POI features
  demo_path: # path for demo features
  image_path:  # path for image features
  mob_graph_path: # path for mobility graph
  batch_size: 20480
  num_workers: 8
  val_random_split_fraction: 0.1
  
watchmodel: True
